memory_limit = 512M
display_errors = On
error_reporting = E_ALL
opcache.enable = 1
opcache.validate_timestamps = 1
pcov.enabled = 1
pcov.directory = /app/apps/api/src
date.timezone = Europe/Madrid

; Documentos de facturas de hasta 10 MB.
upload_max_filesize = 10M
post_max_size = 12M
