memory_limit = 256M
display_errors = Off
expose_php = Off
opcache.enable = 1
opcache.validate_timestamps = 0
opcache.preload_user = www-data
realpath_cache_size = 4096K
date.timezone = Europe/Madrid

; Documentos de facturas de hasta 10 MB.
upload_max_filesize = 10M
post_max_size = 12M
